#!/usr/bin/env bash
#
# Bakes the server URL and API token into the app at build time.
#
# Garmin only exposes Connect IQ app settings in the phone app for apps
# installed from the Connect IQ Store. A sideloaded .prg gets no settings
# screen at all, so for a personally sideloaded build the configuration has to
# be compiled in.
#
# The values are written to resources-local/, which is git-ignored, and layered
# over resources/ by monkey.jungle. Your token therefore never lands in a file
# git tracks -- which matters, since this repo is public.
#
# Usage:  ./configure.sh https://podcasts.example.com <api-token> [episode-limit]

set -euo pipefail
cd "$(dirname "$0")"

URL="${1:-}"
TOKEN="${2:-}"
LIMIT="${3:-10}"

if [ -z "$URL" ] || [ -z "$TOKEN" ]; then
    echo "usage: ./configure.sh <server-url> <api-token> [episode-limit]" >&2
    echo "  e.g. ./configure.sh https://podcasts.example.com Xy7...q2 10" >&2
    exit 1
fi

# Trailing slash would double up against the "/api/v1/..." paths.
URL="${URL%/}"

case "$URL" in
    https://*) ;;
    *) echo "warning: Connect IQ requires HTTPS with a publicly trusted certificate." >&2 ;;
esac

# Escape the XML metacharacters that can legitimately appear in a URL.
xml_escape() {
    printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

mkdir -p resources-local/properties
cat > resources-local/properties/properties.xml <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by configure.sh. Git-ignored: contains a live credential. -->
<properties>
    <property id="serverUrl" type="string">$(xml_escape "$URL")</property>
    <property id="apiToken" type="string">$(xml_escape "$TOKEN")</property>
    <property id="episodeLimit" type="number">$LIMIT</property>
</properties>
EOF

echo "Configured:"
echo "  server URL     $URL"
echo "  API token      ${TOKEN:0:4}...${TOKEN: -4} (${#TOKEN} chars)"
echo "  episode limit  $LIMIT"
echo
echo "Written to resources-local/properties/properties.xml (git-ignored)."
echo "Now rebuild and sideload:"
echo
echo "  monkeyc -f monkey.jungle -o bin/GarminPodcast.prg \\"
echo "      -y ~/.ciq/developer_key.der -d fenix7"
